//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDFDoors.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDFDoors.Shared.Localization.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        public static string DirDoesNotExist {
            get {
                return ResourceManager.GetString("DirDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door Style Saved..
        /// </summary>
        public static string DoorStyleSaved {
            get {
                return ResourceManager.GetString("DoorStyleSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Door Style.
        /// </summary>
        public static string LoadDoorStyle {
            get {
                return ResourceManager.GetString("LoadDoorStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Between.
        /// </summary>
        public static string MultiCopyDistanceHeader {
            get {
                return ResourceManager.GetString("MultiCopyDistanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Copy method.
        /// </summary>
        public static string MultiCopyMethodHeader {
            get {
                return ResourceManager.GetString("MultiCopyMethodHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Copies.
        /// </summary>
        public static string MultipleCopiesTitle {
            get {
                return ResourceManager.GetString("MultipleCopiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Door Style.
        /// </summary>
        public static string SaveDoorStyle {
            get {
                return ResourceManager.GetString("SaveDoorStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDFDoors.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong door style selected..
        /// </summary>
        public static string WrongDoorStyleSelected {
            get {
                return ResourceManager.GetString("WrongDoorStyleSelected", resourceCulture);
            }
        }
    }
}
